# Generated by Django 5.2.4 on 2025-07-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField(unique=True)),
                ('photo', models.ImageField(unique=True, upload_to='staff/')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.position')),
            ],
        ),
    ]
