# Generated by Django 5.2.4 on 2025-07-13 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=20, unique=True)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('UpdateAt', models.DateTimeField(auto_now=True)),
                ('CreateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors_created', to=settings.AUTH_USER_MODEL)),
                ('UpdateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
